### PR TITLE
New Gui Step 1 Output

### PR DESCRIPTION
**Pull request by caleb-james-smith**
New Toggle Igloo Output

### CODE REVIEW

**Comment by caleb-james-smith** [comment]
41
initial = ['1', '1', '1', '1', '1', '1', '1 0']
41
initial = ['0', '0', '0', '0', '0', '0', '0 41']
['0', '0', '0', '0 112 138 191 234 0 0 0 132']
010e1140
Igloo Control =  0 0 7 224
Igloo Ones = 255 255 255 255
Igloo Control =  0 0 3 224
Igloo i2c error detected in detectIglooError
Igloo Ones = 1
Igloo Control =  0 0 7 224
Igloo Ones = 255 255 255 255

**Comment by caleb-james-smith** [comment]
41
initial = ['1', '1', '1', '1', '1', '1', '1 0']
41
initial = ['0', '0', '0', '0', '0', '0', '0 41']
['0', '0', '0', '0 112 138 191 234 0 0 0 132']
010e1140
Igloo Control =  0 0 7 224
Igloo Ones = 255 255 255 255
Igloo Control =  0 0 3 224
Igloo i2c error detected in detectIglooError
Igloo Ones = 1
Igloo Control =  0 0 7 224
Igloo Ones = 255 255 255 255

**Comment by caleb-james-smith** [comment]
I have another updated version to test and include before you merge, my friend! Thanks.

**Comment by shaunhogan** [comment]
Wow it's interesting to be on the other side of a pull request. Accepted!

**Pull request merged**
